### ISSUE TITLE
Meta data for Bittensor 

### ISSUE THREAD

**Issue by Jusbag00** [novasamatech/metadata-portal#852]
Hello, I'm trying to sign a transaction to transfer my TAO, however upon trying to sign for the transaction I'm told to download the latest metadata. Problem being the meta data is out of date? Many thanks

**Comment by Marosseman** [comment]
same issue

**Comment by Jusbag00** [comment]
I hear they are working on the next meta data - 152. Should be ready in 1
/2 days I think.

**Comment by anupsadarangani** [comment]
download it from here and then rename the file to .png instead of apng and scan it'l work i just tried it now and staked some using nova

https://github.com/novasamatech/metadata-portal/pull/851/commits/b126b75a626bd228ccd092d1b2474a99fe6026db#diff-be09f7bccad958f8b7443082188045348d608d4eafdd5a33698c296482f2c42d
